---
title: "Grocery Store Report"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
# Changes and sets working directory
dir<-getwd()
dir<-gsub("R-Scripts","",dir)
setwd(dir)

library(flexdashboard)
library(DT)
source("R-Scripts/kmeans.R")
source("R-Scripts/apriori.R")

{s<-readline("Enter Support:");}
{c<-readline("Enter Confidence:");}
{ncl<-readline("Enter Number of Centers:");}
s<-as.numeric(s)
c<-as.numeric(c)
ncl<-as.numeric(ncl)
rule<-get_ruleset(s,c)
rule<-data.frame("LHS"=rule$LHS,"RHS"=rule$RHS,"Support"=round(rule$support,4),"Confidence"=round(rule$confidence,4),"Lift"=round(rule$lift,4))
k<-calc(ncl)
```

# Summary

## Column {data-width=700, .tabset .tabset-pills }


### Totals By City

```{r}
source("total_spending_byCity.R")
```

### Totals By Age

```{r}
source("totals_by_age.R")
```

### Total Spending Distribution

```{r}
source("total_spending_distribution.R")
chart
```

## Column {data-width=300}


### Cash and Credit Totals

```{r}
source("cash_credit_totals.R")
chart1()
```



# Details

## Column {data-width=500, .tabset .tabset-pills}


### Table

```{r}
datatable(show_table())
```

### Plot

```{r}
show_plot()
```

## Column {data-width=500}

### Association Rules

```{r}
datatable(rule)

```
